export const FETCH_INIT = 'FETCH_INIT';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';

export const SHOW_RECIPE = 'SHOW_RECIPE';
export const MODIFY_RECIPE = 'MODIFY_RECIPE';

export const SELECT_CONTENT = 'SELECT_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
